rm -f *.mv
addr=0000000000000000000000000a550c18

./move-build bank.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move  

mv build/modules/0_ViolasBank.mv bank.mv 

./move-build publish.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv publish.mv 

./move-build register_libra_token.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv register_libra_token.mv 

./move-build enter_bank.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv enter_bank.mv 

./move-build exit_bank.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv exit_bank.mv 

./move-build update_price.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv update_price.mv 

./move-build update_price_from_oracle.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv update_price_from_oracle.mv 

./move-build update_collateral_factor.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv update_collateral_factor.mv 

./move-build update_rate_model.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv update_rate_model.mv 

./move-build lock.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv lock.mv 

./move-build redeem.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv redeem.mv 

./move-build borrow.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv borrow.mv 

./move-build repay_borrow.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv repay_borrow.mv 

./move-build liquidate_borrow.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv liquidate_borrow.mv 

./move-build create_token.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv create_token.mv 

./move-build update_price_index.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv update_price_index.mv 

./move-build mint.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv mint.mv 

./move-build lock_index.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv lock_index.mv 

./move-build redeem_index.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv redeem_index.mv 

./move-build borrow_index.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv borrow_index.mv 

./move-build repay_borrow_index.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv repay_borrow_index.mv 

./move-build liquidate_borrow_index.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv liquidate_borrow_index.mv 

./move-build lock2.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv lock2.mv 

./move-build redeem2.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv redeem2.mv 

./move-build borrow2.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv borrow2.mv 

./move-build repay_borrow2.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv repay_borrow2.mv 

./move-build migrate.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv migrate.mv 

./move-build disable.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv disable.mv 

./move-build test.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv test.mv 

./move-build set_incentive_rate.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv set_incentive_rate.mv 

./move-build set_incentive_rate2.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv set_incentive_rate2.mv 

./move-build claim_incentive.move -s 0x$addr -d modules/SlidingNonce.move modules/ChainId.move modules/AccountCreationScripts.move modules/Errors.move modules/pbank.move modules/Hash.move modules/RecoveryAddress.move modules/AccountAdministrationScripts.move modules/Vector.move modules/AccountFreezing.move modules/DesignatedDealer.move modules/Genesis.move modules/SystemAdministrationScripts.move modules/Roles.move modules/VASP.move modules/DiemVersion.move modules/Authenticator.move modules/DiemTimestamp.move modules/TreasuryComplianceScripts.move modules/oracle.move modules/Signature.move modules/PaymentScripts.move modules/DiemConfig.move modules/TransactionFee.move modules/AccountLimits.move modules/DualAttestation.move modules/ValidatorOperatorConfig.move modules/XDX.move modules/DiemConsensusConfig.move modules/DiemTransactionPublishingOption.move modules/VLS.move modules/DiemVMConfig.move modules/DiemAccount.move modules/Diem.move modules/Option.move modules/SharedEd25519PublicKey.move modules/ValidatorConfig.move modules/RegisteredCurrencies.move modules/CoreAddresses.move modules/Signer.move modules/FixedPoint32.move modules/DiemBlock.move modules/XUS.move modules/BCS.move modules/Event.move modules/ValidatorAdministrationScripts.move modules/DiemSystem.move bank.move 

mv build/scripts/main.mv claim_incentive.mv 

